services:
  fail2ban:
    restart: unless-stopped
    image: linuxserver/fail2ban:1.1.0
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./fail2ban/config:/config
      - /var/log:/var/log:ro
      - ./proxy/nginx:/remotelogs/nginx:ro #optional
  proxy:
    restart: unless-stopped
    image: nginx:1.29
    container_name: proxy
    volumes:
      - ./proxy/prod/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/prod/security-deny.conf:/etc/nginx/security-deny.conf
      - ./proxy/prod/ssl-config.conf:/etc/nginx/ssl-config.conf
      - ./proxy/prod/domain.cert.pem:/etc/ssl/domain.cert.pem
      - ./proxy/prod/private.key.pem:/etc/ssl/private.key.pem
      - ./proxy/prod/robots.txt:/var/www/robots.txt
      - ./proxy/favicon.ico:/var/www/favicon.ico
      - ./proxy/nginx:/var/log/nginx
      - app1-data:/var/www
    networks:
      - proxy_to_app_main
      - proxy_to_app1
      - proxy_to_celery-flower1
      - proxy_to_app2
      - proxy_to_celery-flower2
      - proxy_to_app3
      - proxy_to_celery-flower3
    stop_grace_period: 3m
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app_main
      - app1
      - app2
      - app3
      - celery-flower1
      - celery-flower2
      - celery-flower3
  app_main:
    restart: unless-stopped
    build: ./app_main
    container_name: app_main
    env_file:
      - ./app_main/.env
    volumes:
      - ./app_main:/app
    networks:
      - proxy_to_app_main
    stop_grace_period: 3m
    command: fastapi run app.py --host 0.0.0.0 --port 5000
  app1:
    restart: unless-stopped
    build: ./app1
    container_name: app1
    env_file:
      - ./app1/.env
    volumes:
      - ./app1:/app
      - app1-data:/var/www
    depends_on:
      db1:
        condition: service_healthy
    networks:
      - proxy_to_app1
      - services_for_app1
    stop_grace_period: 3m
    command: gunicorn --worker-tmp-dir /dev/shm "app1.wsgi" -b :5000 --timeout 60 -w 4
    post_start:
      - command: python manage.py makemigrations
      - command: python manage.py migrate
      - command: python manage.py collectstatic --noinput
      - command: python manage.py test
  db1:
    restart: unless-stopped
    image: postgres:18
    container_name: db1
    env_file:
      - ./app1/.env
    volumes:
      - db1-data:/var/lib/postgresql
    networks:
      - services_for_app1
    stop_grace_period: 3m
    healthcheck:
      test: pg_isready -h localhost -U $$POSTGRES_USER || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 1s
  redis1:
    restart: unless-stopped
    image: redis:7
    container_name: redis1
    volumes:
      - redis1-data:/data
    networks:
      - services_for_app1
    stop_grace_period: 3m
  celery-worker1:
    restart: unless-stopped
    build: ./app1
    container_name: celery-worker1
    env_file:
      - ./app1/.env
    volumes:
      - ./app1:/app
    depends_on:
      - app1
      - redis1
    networks:
      - services_for_app1
    stop_grace_period: 3m
    command: celery --app app1 worker --loglevel=info
  celery-beat1:
    restart: unless-stopped
    build: ./app1
    container_name: celery-beat1
    env_file:
      - ./app1/.env
    volumes:
      - ./app1:/app
    depends_on:
      - celery-worker1
    networks:
      - services_for_app1
    stop_grace_period: 3m
    command: celery --app app1 beat --loglevel=info
  celery-flower1:
    restart: unless-stopped
    build: ./app1
    container_name: celery-flower1
    env_file:
      - ./app1/.env
    volumes:
      - ./app1:/app
    depends_on:
      - celery-worker1
      - celery-beat1
    networks:
      - proxy_to_celery-flower1
      - services_for_app1
    stop_grace_period: 3m
    command: celery --app app1 flower
  app2:
    restart: unless-stopped
    build: ./app2
    container_name: app2
    env_file:
      - ./app2/.env
    volumes:
      - ./app2:/app
    depends_on:
      db2:
        condition: service_healthy
    networks:
      - proxy_to_app2
      - services_for_app2
    stop_grace_period: 3m
    command: gunicorn --worker-tmp-dir /dev/shm "app:create_app()" -b :5000 --timeout 60 -w 4
  db2:
    restart: unless-stopped
    image: postgres:18
    container_name: db2
    env_file:
      - ./app2/.env
    volumes:
      - db2-data:/var/lib/postgresql
    networks:
      - services_for_app2
    stop_grace_period: 3m
    healthcheck:
      test: pg_isready -h localhost -U $$POSTGRES_USER || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 1s
  redis2:
    restart: unless-stopped
    image: redis:7
    container_name: redis2
    volumes:
      - redis2-data:/data
    networks:
      - services_for_app2
    stop_grace_period: 3m
  celery-worker2:
    restart: unless-stopped
    build: ./app2
    container_name: celery-worker2
    env_file:
      - ./app2/.env
    volumes:
      - ./app2:/app
    depends_on:
      - app2
      - redis2
    networks:
      - services_for_app2
    stop_grace_period: 3m
    command: celery --app tasks worker --loglevel=info
  celery-beat2:
    restart: unless-stopped
    build: ./app2
    container_name: celery-beat2
    env_file:
      - ./app2/.env
    volumes:
      - ./app2:/app
    depends_on:
      - celery-worker2
    networks:
      - services_for_app2
    stop_grace_period: 3m
    command: celery --app tasks beat --loglevel=info
  celery-flower2:
    restart: unless-stopped
    build: ./app2
    container_name: celery-flower2
    env_file:
      - ./app2/.env
    volumes:
      - ./app2:/app
    depends_on:
      - celery-worker2
      - celery-beat2
    networks:
      - proxy_to_celery-flower2
      - services_for_app2
    stop_grace_period: 3m
    command: celery --app tasks flower
  app3:
    restart: unless-stopped
    build: ./app3
    container_name: app3
    env_file:
      - ./app3/.env
    volumes:
      - ./app3:/app
    networks:
      - proxy_to_app3
      - services_for_app3
    stop_grace_period: 3m
    command: uvicorn app:create_app --factory --host 0.0.0.0 --port 5000 --workers 4
  db3:
    restart: unless-stopped
    image: postgres:18
    container_name: db3
    env_file:
      - ./app3/.env
    volumes:
      - db3-data:/var/lib/postgresql
    networks:
      - services_for_app3
    stop_grace_period: 3m
    healthcheck:
      test: pg_isready -h localhost -U $$POSTGRES_USER || exit 1
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 1s
  redis3:
    restart: unless-stopped
    image: redis:7
    container_name: redis3
    volumes:
      - redis3-data:/data
    networks:
      - services_for_app3
    stop_grace_period: 3m
  celery-worker3:
    restart: unless-stopped
    build: ./app3
    container_name: celery-worker3
    env_file:
      - ./app3/.env
    volumes:
      - ./app3:/app
    depends_on:
      - app3
      - redis3
    networks:
      - services_for_app3
    stop_grace_period: 3m
    command: celery --app tasks worker --loglevel=info
  celery-beat3:
    restart: unless-stopped
    build: ./app3
    container_name: celery-beat3
    env_file:
      - ./app3/.env
    volumes:
      - ./app3:/app
    depends_on:
      - celery-worker3
    networks:
      - services_for_app3
    stop_grace_period: 3m
    command: celery --app tasks beat --loglevel=info
  celery-flower3:
    restart: unless-stopped
    build: ./app3
    container_name: celery-flower3
    env_file:
      - ./app3/.env
    volumes:
      - ./app3:/app
    depends_on:
      - celery-worker3
      - celery-beat3
    networks:
      - proxy_to_celery-flower3
      - services_for_app3
    stop_grace_period: 3m
    command: celery --app tasks flower
volumes:
  app1-data:
  db1-data:
  redis1-data:
  db2-data:
  redis2-data:
  db3-data:
  redis3-data:
networks:
  proxy_to_app_main:
  proxy_to_app1:
  proxy_to_celery-flower1:
  services_for_app1:
  proxy_to_app2:
  proxy_to_celery-flower2:
  services_for_app2:
  proxy_to_app3:
  proxy_to_celery-flower3:
  services_for_app3:
