import datetime
import os
DEBUG = False
SQLALCHEMY_DATABASE_URI = f'postgresql://postgres:{os.environ.get("POSTGRES_PASSWORD")}@auth-db:5432'
SQLALCHEMY_TRACK_MODIFICATIONS = False
PROPAGATE_EXCEPTIONS = True
JWT_TOKEN_LOCATION = ['cookies']
JWT_COOKIE_SECURE = True
JWT_ACCESS_TOKEN_EXPIRES = datetime.timedelta(hours=6)
JWT_COOKIE_CSRF_PROTECT = True
JWT_CSRF_IN_COOKIES = False
JWT_COOKIE_SAMESITE = 'Lax'
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ['access', 'refresh']
CELERY_BROKER_URL = 'redis://redis2:6379'
CELERY_RESULT_BACKEND = 'redis://redis2:6379'
