# Deny .git access
location ~* /\.git(/|$) {
    deny all;
    return 403;
}

# Deny .env access
location ~* /\.env(/|$) {
    deny all;
    return 403;
}

# Deny wp-content
location ~* /wp-content(.*)+$ {
    deny all;
    return 403;
}

# Deny wp-admin
location ~* /wp-admin(.*)+$ {
    deny all;
    return 403;
}

# Deny wp-includes/wlwmanifest and similar
location ~* /wp-includes(.*)+$ {
    deny all;
    return 403;
}

# Deny suspicious .php file patterns
location ~* \.php[\d\w]+$ {
    deny all;
    return 403;
}

# Deny all .php files by default
location ~* \.php$ {
    deny all;
    return 403;
}

# Deny requests without handler like browser
if ($http_user_agent = "") {
    return 444;
}

# Deny nonstandard REST requests
if ($request_method !~ ^(GET|POST|PUT|DELETE|PATCH)$) {
    return 444;
}
